### ISSUE TITLE
glitchy water 

### ISSUE THREAD

**Issue by moovamps666** [jebbyk/OSBES-minecraft-bedrock-edition-shader#190] opened 2021-07-10 18:53 UTC
hi! i recently started using this shader, and it's really pretty, but i have an issue with the water. 
it appears to be glitchy, and it happens almost all the time i create a new world and use my usual addons. idk if this is an issue with the addons, or with the shader.
i'll insert some screenshots.

![Screenshot_20210710_134336_com mojang minecraftpe](https://user-images.githubusercontent.com/87243815/125173670-f8713200-e185-11eb-9ea6-3237e22eff2b.jpg)

![Screenshot_20210710_134328_com mojang minecraftpe](https://user-images.githubusercontent.com/87243815/125173671-f9a25f00-e185-11eb-9db4-89dc4611da2f.jpg)

![Screenshot_20210710_134345_com mojang minecraftpe](https://user-images.githubusercontent.com/87243815/125173668-f6a76e80-e185-11eb-90ae-a73317cc84e7.jpg)

![Screenshot_20210710_134404_com mojang minecraftpe](https://user-images.githubusercontent.com/87243815/125173666-f4ddab00-e185-11eb-920b-a30ba5e6ab45.jpg)

![Screenshot_20210710_134422_com mojang minecraftpe](https://user-images.githubusercontent.com/87243815/125173661-eabbac80-e185-11eb-916e-2a4a36ce4a01.jpg)

how can i fix this? :( 
i would really like to play with this shader :(

**Comment by OpenSauce04** [comment] 2021-07-10 21:16
The issue is your addons, they must be interfering with the texture atlas in some way

**Comment by jebbyk** [comment] 2021-07-11 01:34
@moovamps666 can you please tell me which add-ons are you using?

**Comment by moovamps666** [comment] 2021-07-11 05:25
sure! i'm using ghoulcraft, mikoto addon and moondrop food! i'm using yfarmcraft, ycreatures and ybiomes too, but i didn't have an issue when i was using them on their own!

**Comment by jebbyk** [comment] 2021-07-12 07:39
ok thanks, I will check all of these add-ons and improve compatibiltiy if possible

**Comment by moovamps666** [comment] 2021-07-12 13:13
thank u so much!! (*´˘`*)♡

**Comment by jebbyk** [comment] 2022-01-16 10:51
should be fixed

**Closed as completed by jebbyk** 2022-01-16 10:51 UTC
Labels: rare/not critical  bug
