### ISSUE TITLE
Glitched block icons

### ISSUE THREAD

**Issue by Demon-Ak** [jebbyk/OSBES-minecraft-bedrock-edition-shader#159] opened 2021-06-01 15:42 UTC
When I open the inventory all the blocks icons are glitched and you can't know which block that you have chose till you place it in the world but everything else is okay
Examples:
![Screenshot_2021-05-25-15-05-51-222_com mojang minecraftpe](https://user-images.githubusercontent.com/84788001/120351744-08c8fe00-c2f8-11eb-9b40-08eadfbea1ac.jpg)

![Screenshot_2021-05-25-15-05-41-404_com mojang minecraftpe](https://user-images.githubusercontent.com/84788001/120351779-11b9cf80-c2f8-11eb-85d8-cf210d759b15.jpg)

**Comment by Demon-Ak** [comment] 2021-06-01 15:45
I actually said that before but you thought that it a spam
So I resend it....hope you fix it

**Comment by jebbyk** [comment] 2021-06-02 03:02
is it x64 pack?

**Comment by vannnemcee** [comment] 2021-06-05 07:36
Yes, it's a x64 pack.I've also experienced the bug, please fix it as soon as possible

**Comment by Demon-Ak** [comment] 2021-06-05 14:13
Yas it is a x64 pac

**Comment by Demon-Ak** [comment] 2021-06-05 14:14
Yas it is a x64 pack

**Comment by jebbyk** [comment] 2021-06-05 18:31
x64 packs are not fully supported at the moment

**Comment by Demon-Ak** [comment] 2021-06-06 13:14
Ohh it okay then I can work with the shader like that

**Comment by jebbyk** [comment] 2021-06-08 05:58
are you trying to make a texturepack?

**Comment by Demon-Ak** [comment] 2021-06-11 16:21
Owwww no not at all I just meant that I can play with the glitched blocks icons

**Comment by AverageCrafter** [comment] 2021-06-13 03:11
There's some buggy blocks that need to be fixed, here's a link to the photo since I can't drag a file herehttps://mobile.twitter.com/CinenRalph/status/1403912486680555529

**Comment by AverageCrafter** [comment] 2021-06-13 03:13
There's some buggy blocks that need to be fixed. An example for the textures  ![Screenshot_20210622-204025_Minecraft](https://user-images.githubusercontent.com/85814724/123021813-62be6000-d39a-11eb-8a62-e9a39533a3f2.jpg) ![Screenshot_20210622-204038_Minecraft](https://user-images.githubusercontent.com/85814724/123021829-67831400-d39a-11eb-9fa4-d8e6e343954b.jpg) ![Screenshot_20210622-204055_Minecraft](https://user-images.githubusercontent.com/85814724/123021836-6ce05e80-d39a-11eb-8320-99669f4a0b6d.jpg) ![Screenshot_20210622-204001_Minecraft](https://user-images.githubusercontent.com/85814724/123021775-533f1700-d39a-11eb-9e35-013a45ab3a3d.jpg) ![Screenshot_20210622-204015_Minecraft](https://user-images.githubusercontent.com/85814724/123021803-5f2ad900-d39a-11eb-8764-f16dfc4c944d.jpg)

**Comment by Demon-Ak** [comment] 2021-06-14 12:34
> There's some buggy blocks that need to be fixed, here's a link since I'm on mobile. https://mobile.twitter.com/CinenRalph/status/1403912486680555529

Yo bro you can post pics even if your on mobile i did that

**Comment by vannnemcee** [comment] 2021-06-14 18:07
To the developer, I want to ask why the shaders rarely update, the problem is that Minecraft is already version 1.17

**Comment by AverageCrafter** [comment] 2021-06-14 19:21
The issue is fixed with minor changes, the problems people still have are the texture with blocks and the water

**Comment by vannnemcee** [comment] 2021-06-16 09:23
Let me ask again. when's the osbes update?

**Comment by jebbyk** [comment] 2021-06-17 04:18
you can download zip file from this repository. It already should not have any texture bugs in 1.17.

**Comment by vannnemcee** [comment] 2021-06-18 13:39
do you think the OSBES update is on what date or what month?

**Comment by AverageCrafter** [comment] 2021-06-19 22:22
> you can download zip file from this repository. It already should not have any texture bugs in 1.17.

Can you link it?

**Comment by AverageCrafter** [comment] 2021-06-19 22:36
> you can download zip file from this repository. It already should not have any texture bugs in 1.17.

I downloaded it and it was the exact same thing. No fixes were in it

**Comment by jebbyk** [comment] 2021-07-09 09:10
block icons issue is fixed for regular texture packs and for 16x pbr texture packs

**Closed as completed by jebbyk** 2021-07-09 09:10 UTC
